/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DashboardPackage;

import Config.Koneksi;
import LoginPackage.JFrameLogin;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class JFrameHomeEmployee extends javax.swing.JFrame {
    
    private String username;
    private String level;
    private String conn;

    /**
     * Creates new form JFrameHomeEmployee
     */
    public JFrameHomeEmployee() {
        initComponents();
//      penangkapan variable login dari JframeLogin untuk ditampilkan kedalam label
        this.username = "Default";
        this.level = "Default";
        labelUser.setText(this.username);
        labelLevel.setText(this.level);
        
        
    }
    public JFrameHomeEmployee(String username, String level) {
        initComponents();
        
        // Inisialisasi nilai username dan level dari JFrameLogin
        this.username = username;
        this.level = level;

        // Atur nilai label sesuai dengan username dan level
        labelUser.setText(this.level);
        labelLevel.setText(this.username);
        //Switch Menu Panel
        PanelDashboard.setVisible(true);
        PanelAttendance.setVisible(false);
        PanelAnnouncement.setVisible(false);
        PanelAbout.setVisible(false);
        panelLogout.setVisible(false);
        
        //Main menu panel Switch
        Dashboard.setVisible(true);
        Attendance.setVisible(false);
        Announcement.setVisible(false);
        About.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        PanelMenu = new keeptoo.KGradientPanel();
        PanelMenu1 = new keeptoo.KGradientPanel();
        labelUser = new javax.swing.JLabel();
        labelLevel = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        PanelMenuHead = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        labelDashboard = new javax.swing.JLabel();
        labelAttendance = new javax.swing.JLabel();
        labelAnnouncement = new javax.swing.JLabel();
        labelAbout = new javax.swing.JLabel();
        labelLogout = new javax.swing.JLabel();
        PanelDashboard = new javax.swing.JPanel();
        PanelAttendance = new javax.swing.JPanel();
        PanelAnnouncement = new javax.swing.JPanel();
        PanelAbout = new javax.swing.JPanel();
        panelLogout = new javax.swing.JPanel();
        Dashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelBox1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelLine = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        panelBox2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        panelLine1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        panelChart = new javax.swing.JPanel();
        panelLineChart = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        panelBarChart = new javax.swing.JPanel();
        jLabel44 = new javax.swing.JLabel();
        PanelNavbar = new javax.swing.JPanel();
        About = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        gbr_gedung = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        Announcement = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Attendance = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        panelFormAttn = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        radioBtnPresent = new javax.swing.JRadioButton();
        radioBtnLate = new javax.swing.JRadioButton();
        radioBtnPermission = new javax.swing.JRadioButton();
        radioBtnAlpha = new javax.swing.JRadioButton();
        jLabel21 = new javax.swing.JLabel();
        datePicker = new org.jdesktop.swingx.JXDatePicker();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        txtNip = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu.setkEndColor(new java.awt.Color(255, 255, 255));
        PanelMenu.setkStartColor(new java.awt.Color(86, 177, 222));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        PanelMenu1.setkEndColor(new java.awt.Color(204, 204, 204));
        PanelMenu1.setkStartColor(new java.awt.Color(86, 177, 222));
        PanelMenu1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelUser.setText("level");
        PanelMenu1.add(labelUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 90, 20));

        labelLevel.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        labelLevel.setText("user");
        PanelMenu1.add(labelLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 90, 20));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/profile2.png"))); // NOI18N
        PanelMenu1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        PanelMenuHead.setBackground(new java.awt.Color(0, 153, 204));
        PanelMenuHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Company");
        PanelMenuHead.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jLabel5.setFont(new java.awt.Font("Dubai", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("App");
        PanelMenuHead.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, -1, 20));

        PanelMenu1.add(PanelMenuHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jLabel15.setFont(new java.awt.Font("Franklin Gothic Demi", 0, 16)); // NOI18N
        jLabel15.setText("Welcome !");
        PanelMenu1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 80, -1));

        PanelMenu.add(PanelMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 160));

        labelDashboard.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        labelDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/dashboardIcon.png"))); // NOI18N
        labelDashboard.setText("Dashboard");
        labelDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDashboardMouseClicked(evt);
            }
        });
        PanelMenu.add(labelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        labelAttendance.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        labelAttendance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/AttendanceIcon.png"))); // NOI18N
        labelAttendance.setText("Attendance");
        labelAttendance.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAttendance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAttendanceMouseClicked(evt);
            }
        });
        PanelMenu.add(labelAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        labelAnnouncement.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        labelAnnouncement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/announcement.png"))); // NOI18N
        labelAnnouncement.setText("Announcement");
        labelAnnouncement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAnnouncement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAnnouncementMouseClicked(evt);
            }
        });
        PanelMenu.add(labelAnnouncement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        labelAbout.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        labelAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/aboutIcon.png"))); // NOI18N
        labelAbout.setText("About");
        labelAbout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAboutMouseClicked(evt);
            }
        });
        PanelMenu.add(labelAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        labelLogout.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        labelLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/logoutIcon.png"))); // NOI18N
        labelLogout.setText("Logout");
        labelLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        labelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogoutMouseClicked(evt);
            }
        });
        PanelMenu.add(labelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        PanelDashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelMenu.add(PanelDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 200, 40));

        PanelAttendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelMenu.add(PanelAttendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 200, 40));

        PanelAnnouncement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelMenu.add(PanelAnnouncement, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 200, 40));

        PanelAbout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelMenu.add(PanelAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 40));

        panelLogout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        PanelMenu.add(panelLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 200, 40));

        panelUtama.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 700));

        Dashboard.setBackground(new java.awt.Color(255, 255, 255));
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dubai", 1, 25)); // NOI18N
        jLabel1.setText("DASHBOARD");
        Dashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 40));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel3.setText("Overview & Statistic");
        Dashboard.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        panelBox1.setBackground(new java.awt.Color(255, 255, 255));
        panelBox1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        panelBox1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel6.setText("Karyawan");
        panelBox1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel8.setText("120");
        panelBox1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 255));
        jLabel9.setText("Employee Data Table");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBox1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        panelLine.setBackground(new java.awt.Color(255, 255, 255));
        panelLine.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        panelLine.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBox1.add(panelLine, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 10));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/userIcon.png"))); // NOI18N
        panelBox1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, 80));

        Dashboard.add(panelBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, 140));

        panelBox2.setBackground(new java.awt.Color(255, 255, 255));
        panelBox2.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        panelBox2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/userIcon.png"))); // NOI18N
        panelBox2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 70, 80));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        jLabel11.setText("Pelamar");
        panelBox2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel12.setText("40");
        panelBox2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        panelLine1.setBackground(new java.awt.Color(255, 255, 255));
        panelLine1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        panelLine1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelBox2.add(panelLine1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 10));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB", 0, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 102, 255));
        jLabel13.setText("Applicant Data Table");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBox2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        Dashboard.add(panelBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 190, 140));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB", 0, 20)); // NOI18N
        jLabel14.setText("Bar Chart");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        Dashboard.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 610, 40));

        panelChart.setBackground(new java.awt.Color(255, 255, 255));
        panelChart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelChart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLineChart.setBackground(new java.awt.Color(255, 255, 255));
        panelLineChart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 0, 0)));
        panelLineChart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/barchartImg.png"))); // NOI18N
        panelLineChart.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panelChart.add(panelLineChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, 210));

        panelBarChart.setBackground(new java.awt.Color(255, 255, 255));
        panelBarChart.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/pychartImg_1.png"))); // NOI18N
        panelBarChart.add(jLabel44);

        panelChart.add(panelBarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 260, 210));

        Dashboard.add(panelChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 610, 260));

        panelUtama.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 700, 650));

        PanelNavbar.setBackground(new java.awt.Color(86, 177, 222));
        PanelNavbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelUtama.add(PanelNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        About.setBackground(new java.awt.Color(255, 255, 255));
        About.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Candara", 1, 22)); // NOI18N
        jLabel2.setText("About Us");
        About.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setText("PT Company FFA, founded in 2024, is a leader in the field of Technology.");
        About.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setText("The focus on innovation, quality and superior service makes it the top choice in the market.");
        About.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setText("With a vision of becoming something, PT Company FFA is also active in social responsibility and sustainability.");
        About.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setText("His high dedication makes him a trusted partner and positive contributor in various aspects.");
        About.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        gbr_gedung.setBackground(new java.awt.Color(255, 255, 255));
        gbr_gedung.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/about.jpg"))); // NOI18N
        gbr_gedung.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 650, 310));

        About.add(gbr_gedung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 700, 360));

        panelUtama.add(About, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 700, 650));

        Announcement.setBackground(new java.awt.Color(255, 255, 255));
        Announcement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel23.setText("Announcement !");
        Announcement.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Asset/meeting.jpg"))); // NOI18N
        Announcement.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel39.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel39.setText("Meeting Conference will be held At White House October 28 - 29 2024");
        Announcement.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel24.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel24.setText("We are pleased to announce that the business meeting conference will be held on [date] at [time].");
        Announcement.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jLabel41.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel41.setText("Let's attend this event together to discuss opportunities for collaboration and innovation in the ");
        Announcement.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 580, -1));

        jLabel42.setText("world of business.");
        Announcement.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, -1, -1));

        panelUtama.add(Announcement, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 700, 650));

        Attendance.setBackground(new java.awt.Color(255, 255, 255));
        Attendance.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Berlin Sans FB", 0, 25)); // NOI18N
        jLabel18.setText("ATTENDANCE");
        Attendance.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel19.setText("Fulfill Your Attendantion To Get A Good Reputation");
        Attendance.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("Please Fill Your Presence");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 50));

        Attendance.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 640, 50));

        panelFormAttn.setBackground(new java.awt.Color(153, 204, 255));
        panelFormAttn.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        panelFormAttn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setText("Status");
        panelFormAttn.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        radioBtnPresent.setBackground(new java.awt.Color(153, 204, 255));
        radioBtnPresent.setText("Present");
        panelFormAttn.add(radioBtnPresent, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        radioBtnLate.setBackground(new java.awt.Color(153, 204, 255));
        radioBtnLate.setText("Late");
        panelFormAttn.add(radioBtnLate, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        radioBtnPermission.setBackground(new java.awt.Color(153, 204, 255));
        radioBtnPermission.setText("Permission");
        panelFormAttn.add(radioBtnPermission, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        radioBtnAlpha.setBackground(new java.awt.Color(153, 204, 255));
        radioBtnAlpha.setText("Alpha");
        panelFormAttn.add(radioBtnAlpha, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel21.setText("Select Date");
        panelFormAttn.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        panelFormAttn.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        rSMaterialButtonRectangle1.setText("Submit");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });
        panelFormAttn.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 100, 40));
        panelFormAttn.add(txtNip, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 180, -1));

        jLabel34.setText("Insert NIP");
        panelFormAttn.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        Attendance.add(panelFormAttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 640, 200));

        panelUtama.add(Attendance, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 700, 650));

        getContentPane().add(panelUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 1, 900, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void labelDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDashboardMouseClicked
        //Switch Menu Panel
        PanelDashboard.setVisible(true);
        PanelAttendance.setVisible(false);
        PanelAnnouncement.setVisible(false);
        PanelAbout.setVisible(false);
        panelLogout.setVisible(false);
        
        //Main menu panel Switch
        Dashboard.setVisible(true);
        Attendance.setVisible(false);
        Announcement.setVisible(false);
        About.setVisible(false);
    }//GEN-LAST:event_labelDashboardMouseClicked

    private void labelAttendanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAttendanceMouseClicked
        //Switch Menu Panel
        PanelDashboard.setVisible(false);
        PanelAttendance.setVisible(true);
        PanelAnnouncement.setVisible(false);
        PanelAbout.setVisible(false);
        panelLogout.setVisible(false);
        
        //Main menu panel Switch
        Dashboard.setVisible(false);
        Attendance.setVisible(true);
        Announcement.setVisible(false);
        About.setVisible(false);
    }//GEN-LAST:event_labelAttendanceMouseClicked

    private void labelAnnouncementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAnnouncementMouseClicked
        //Switch Menu Panel
        PanelDashboard.setVisible(false);
        PanelAttendance.setVisible(false);
        PanelAnnouncement.setVisible(true);
        PanelAbout.setVisible(false);
        panelLogout.setVisible(false);
        
        //Main menu panel Switch
        Dashboard.setVisible(false);
        Attendance.setVisible(false);
        Announcement.setVisible(true);
        About.setVisible(false);
    }//GEN-LAST:event_labelAnnouncementMouseClicked

    private void labelAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAboutMouseClicked
        //Switch Menu Panel
        PanelDashboard.setVisible(false);
        PanelAttendance.setVisible(false);
        PanelAnnouncement.setVisible(false);
        PanelAbout.setVisible(true);
        panelLogout.setVisible(false);
        
        //Main menu panel Switch
        Dashboard.setVisible(false);
        Attendance.setVisible(false);
        Announcement.setVisible(false);
        About.setVisible(true);
    }//GEN-LAST:event_labelAboutMouseClicked

    private void labelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogoutMouseClicked
        PanelDashboard.setVisible(false);
        PanelAttendance.setVisible(false);
        PanelAnnouncement.setVisible(false);
        PanelAbout.setVisible(false);
        panelLogout.setVisible(true);

        int jawaban = JOptionPane.showConfirmDialog(null, "Yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (jawaban == JOptionPane.YES_OPTION) {
            System.out.println("Anda memilih keluar.");
            this.dispose();
            JFrameLogin Login = new JFrameLogin();
            Login.show();
        } else {
            System.out.println("Anda membatalkan keluar.");
            // Tambahkan kode untuk menangani pembatalan di sini, jika diperlukan
        }

    }//GEN-LAST:event_labelLogoutMouseClicked

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        try{
            String sql = "INSERT INTO attendance (nip, tanggal, keterangan, nama) SELECT ?, ?, ?, nama FROM user WHERE nip = ?";
            Connection conn = Koneksi.getConnection();
            PreparedStatement pstm = conn.prepareStatement(sql);

            pstm.setString(1, txtNip.getText());
            pstm.setDate(2, new java.sql.Date(datePicker.getDate().getTime()));
            if (radioBtnPresent.isSelected()) {
                pstm.setString(3, "Present");
            } else if (radioBtnLate.isSelected()) {
                pstm.setString(3, "Late");
            } else if (radioBtnPermission.isSelected()) {
                pstm.setString(3, "Permission");
            } else if (radioBtnAlpha.isSelected()) {
                pstm.setString(3, "Alpha");
            }
            pstm.setString(4, txtNip.getText());

            pstm.executeUpdate();
            JOptionPane.showMessageDialog(null, "Proses Simpan Data Berhasil..");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameHomeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameHomeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameHomeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameHomeEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameHomeEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel About;
    private javax.swing.JPanel Announcement;
    private javax.swing.JPanel Attendance;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JPanel PanelAbout;
    private javax.swing.JPanel PanelAnnouncement;
    private javax.swing.JPanel PanelAttendance;
    private javax.swing.JPanel PanelDashboard;
    private keeptoo.KGradientPanel PanelMenu;
    private keeptoo.KGradientPanel PanelMenu1;
    private javax.swing.JPanel PanelMenuHead;
    private javax.swing.JPanel PanelNavbar;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JPanel gbr_gedung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAbout;
    private javax.swing.JLabel labelAnnouncement;
    private javax.swing.JLabel labelAttendance;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelLevel;
    private javax.swing.JLabel labelLogout;
    private javax.swing.JLabel labelUser;
    private javax.swing.JPanel panelBarChart;
    private javax.swing.JPanel panelBox1;
    private javax.swing.JPanel panelBox2;
    private javax.swing.JPanel panelChart;
    private javax.swing.JPanel panelFormAttn;
    private javax.swing.JPanel panelLine;
    private javax.swing.JPanel panelLine1;
    private javax.swing.JPanel panelLineChart;
    private javax.swing.JPanel panelLogout;
    private javax.swing.JPanel panelUtama;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private javax.swing.JRadioButton radioBtnAlpha;
    private javax.swing.JRadioButton radioBtnLate;
    private javax.swing.JRadioButton radioBtnPermission;
    private javax.swing.JRadioButton radioBtnPresent;
    private javax.swing.JTextField txtNip;
    // End of variables declaration//GEN-END:variables
}
